export const THEMES = {
  dark: {
    sidebar: 'bg-[#0c0c0c]',
    rail: 'bg-[#0a0a0a]',
    canvas: 'bg-[#070707]',
    border: 'border-white/10',
    text: 'text-white',
    title: 'text-white/60',
    item: 'bg-white/5',
    activeItem: 'bg-white/10',
    grid: '#222',
  },
  medium: {
    sidebar: 'bg-[#1a1a1a]', 
    rail: 'bg-[#151515]',
    canvas: 'bg-[#121212]',
    border: 'border-white/10',
    text: 'text-white',
    title: 'text-white/50',
    item: 'bg-white/[0.03]',
    activeItem: 'bg-white/10',
    grid: '#333',
  },
  gray: {
    sidebar: 'bg-gray-100',
    rail: 'bg-gray-200',
    canvas: 'bg-white',
    border: 'border-gray-200',
    text: 'text-black',
    title: 'text-gray-500',
    item: 'bg-white',
    activeItem: 'bg-blue-600 shadow-lg !text-white',
    grid: '#cbd5e1',
  },
  light: {
    sidebar: 'bg-white',
    rail: 'bg-gray-50',
    canvas: 'bg-gray-100',
    border: 'border-gray-200',
    text: 'text-black',
    title: 'text-gray-500',
    item: 'bg-gray-50/50',
    activeItem: 'bg-blue-600 shadow-lg !text-white',
    grid: '#94a3b8',
  }
};
